version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - ./dev/data:/data/db
    networks:
      - inet
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpwd
      - MONGO_INITDB_DATABASE=admin
      - MONGO_DATABASE=cdn

  cdn:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    restart: on-failure
    volumes:
      - ${APP_SRC}:/app
      - ${APP_SRC}/buckets:/data/buckets
      - /app/docker/dev/data
      - /app/buckets
    depends_on:
      - mongo
    environment:
      - MONGO_URI
      - MONGO_DB_NAME
      - APP_PORT
      - DOMAIN
      - APP_HOST
    ports:
      - "5000:5000"
    networks:
      - inet

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${APP_SRC}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - inet

  grafana:
    image: grafana/grafana
    user: root
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ${APP_SRC}/grafana/provisioning:/etc/grafana/provisioning
      - ${APP_SRC}/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - inet


networks:
  inet:
    driver: bridge

